"""initial_schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-08-24 22:30:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, default=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True, default=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.String(length=100), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False, default="INR"),
        sa.Column("status", sa.String(length=50), nullable=False, default="pending"),
        sa.Column("strategy_used", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recovery_cases_id"), "recovery_cases", ["id"], unique=False)
    op.create_index(op.f("ix_recovery_cases_invoice_id"), "recovery_cases", ["invoice_id"], unique=True)
    op.create_index(op.f("ix_recovery_cases_customer_email"), "recovery_cases", ["customer_email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_recovery_cases_customer_email"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_invoice_id"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_id"), table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
